# vim:ft=kitty

## name:     Catppuccin Kitty Macchiato
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/macchiato.conf
## blurb:    Soothing pastel theme for the high-spirited!

## Modified by JD on 2026-05-13 to match order of .config/kitty/kitty.conf.


cursor                  #f4dbd6
cursor_text_color       #24273a

#: Default text cursor color and color of text under the cursor.

scrollbar_handle_color  #939ab7
scrollbar_track_color   #494d64

#: The color of the scrollbar handle and track.

url_color               #f4dbd6

#: The color for highlighting URLs on mouse-over.

active_tab_foreground   #181926
active_tab_background   #c6a0f6
inactive_tab_foreground #cad3f5
inactive_tab_background #1e2030

#: Tab bar colors and styles.

tab_bar_background      #181926

#: Tab bar backround color.

foreground              #cad3f5
background              #24273a

#: The foreground and background colors.

selection_foreground    #24273a
selection_background    #f4dbd6

#: The foreground and background colors for text selected with the mouse.

active_border_color     #b7bdf8
inactive_border_color   #6e738d
bell_border_color       #eed49f

#: The color for the border of the active window, all inactive windows,
#: and any windows in which a bell has occurred, respectively.

wayland_titlebar_color system

#: The color of the kitty window's titlebar on Wayland systems with
#: client side window decorations.

# The 16 basic terminal colors, dull and bright.

color0 #494d64
color8 #5b6078

#: black

color1 #ed8796
color9 #ed8796

#: red

color2  #a6da95
color10 #a6da95

#: green

color3  #eed49f
color11 #eed49f

#: yellow

color4  #8aadf4
color12 #8aadf4

#: blue

color5  #f5bde6
color13 #f5bde6

#: magenta

color6  #8bd5ca
color14 #8bd5ca

#: cyan

color7  #b8c0e0
color15 #a5adcb

#: white

mark1_foreground #24273a
mark1_background #b7bdf8
mark2_foreground #24273a
mark2_background #c6a0f6
mark3_foreground #24273a
mark3_background #7dc4e4

#: Colors for marked text in the terminal.
